name: Build and Push Docker Image

on:
  push:
    branches:
      - staging
      - dev
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    services:
      dockerd:
        image: docker:latest

    needs: build-nodejs-app

    steps:
      - uses: actions/checkout@v4

        
      - name: Print Docker Info
        run: docker info
        
      - name: Print Node.js Version
        run: node -v

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: techlead-midland
          password: ${{ secrets.GHCR_PAT }}

      
          
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/techlead-midland/midland-microfin-ltd/uptime-kuma
          docker push ghcr.io/techlead-midland/midland-microfin-ltd/uptime-kuma
